CREATE TABLE IF NOT EXISTS sec.policy (
  id SERIAL NOT NULL,
  name CHARACTER VARYING(45) NOT NULL,
  description CHARACTER VARYING(255),

  data JSONB,

  org_id INT,
  role_type_id INT,

  is_active BOOLEAN DEFAULT TRUE,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  created_by CHARACTER VARYING(45) DEFAULT CURRENT_USER,
  updated_by CHARACTER VARYING(45),
  --
  PRIMARY KEY(id),
  FOREIGN KEY(role_type_id) REFERENCES dbo.role_type(id) ON DELETE SET NULL
);