export enum ActionClickType {
  MENU_EDIT = 'MENU_EDIT',
  MENU_CLONE = 'MENU_CLONE',
  MENU_REMOVE = 'MENU_REMOVE',

  EDITOR_CLOSE = 'EDITOR_CLOSE',
  EDITOR_SAVE = 'EDITOR_SAVE',
  EDITOR_RESET = 'EDITOR_RESET',

  FORM_SUBMIT = 'FORM_SUBMIT',
  FORM_RESET = 'FORM_RESET'
}

export enum ActionMenuEnum {
  MENU_EDIT = 'MENU_EDIT',
  MENU_CLONE = 'MENU_CLONE',
  MENU_REMOVE = 'MENU_REMOVE'
}

export enum ActionEditorEnum {
  EDITOR_CLOSE = 'EDITOR_CLOSE',
  EDITOR_SAVE = 'EDITOR_SAVE',
  EDITOR_RESET = 'EDITOR_RESET',
}

export enum ActionFormEnum {
  FORM_SUBMIT = 'FORM_SUBMIT',
  FORM_RESET = 'FORM_RESET',
}


