export enum AppStatus {
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  AUTHENTICATED = 'AUTHENTICATED',
  INACTIVE = 'INACTIVE',
  REQUIRE_VERIFY = 'REQUIRE_VERIFY',
  REQUIRE_VERIFY_COMPANY = 'REQUIRE_VERIFY_COMPANY',
}
