export enum AppStatus {
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  REQUIRE_VERIFY_COMPANY = 'REQUIRE_VERIFY_COMPANY',
  REQUIRE_VERIFY = 'REQUIRE_VERIFY',
}
