export enum UserStatus {
  NOT_FOUND = 'USER_NOT_FOUND',
  ACTIVE = 'USER_ACTIVE',
  INACTIVE = 'USER_INACTIVE',
  REQUIRE_COMPANY = 'USER_REQUIRE_COMPANY',
  REQUIRE_VERIFY = 'USER_REQUIRE_VERIFY',
}
