version: '3.7'
services:
  nest_app:
    build:
      context: ./nest-app
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev nest_app
    env_file:
      - ./nest-app/.env
    ports:
      - '5000:5000'
    environment:
      - POSTGRES_HOST=host.docker.internal
      - REDIS_HOST=host.docker.internal
      - SEND_HOST=nest_sender
      - WORKER_HOST=nest_worker
    extra_hosts:
      - "host.docker.internal:host-gateway" #window
      #- "host.docker.internal: 172.17.0.1"
    volumes:
      - ./nest-app:/usr/src/app
  nest_sender:
    build:
      context: ./nest-sender
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev nest_sender
    env_file:
      - ./nest-sender/.env
    environment:
      - POSTGRES_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway" #window
      #- "host.docker.internal: 172.17.0.1"
    volumes:
      - ./nest-sender:/usr/src/app
  nest_worker:
    build:
      context: ./nest-worker
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev nest_worker
    env_file:
      - ./nest-worker/.env
    environment:
      - POSTGRES_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway" #window
      #- "host.docker.internal: 172.17.0.1"
    volumes:
      - ./nest-worker:/usr/src/app
