services:
  nest_app:
    build:
      context: ./nest-app
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev nest_app
    ports:
      - '5000:5000'
    environment:
      - POSTGRES_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nest-app:/usr/src/app
  nest_notification:
    build:
      context: ./nest-notification
      dockerfile: ./Dockerfile
      target: development