export const utilFunctionsAndPlugins = {
  scripts: [
    // TYPES
    {
      id: 100,
      databaseName: 'db_app',
      schemaName: 'public',
      objectType: 'type',
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'type_user_role_info',
      scriptType: 'sql',
      scriptOrder: '100',
      scriptPath: 'db_app/public/util/types/type_user_role_info.sql',
    },

    // FUNCTIONS
    {
      id: 200,
      databaseName: 'db_app',
      schemaName: 'public',
      objectType: 'function',
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'fn_util_camel_case_split',
      scriptType: 'sql',
      scriptOrder: '200',
      scriptPath: 'db_app/public/util/functions/fn_util_camel_case_split.sql',
    },
    {
      id: 201,
      databaseName: 'db_app',
      schemaName: 'public',
      objectType: 'function',
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'fn_util_generate_random_string',
      scriptType: 'sql',
      scriptOrder: '201',
      scriptPath: 'db_app/public/util/functions/fn_util_generate_random_string.sql',
    },
    {
      id: 202,
      databaseName: 'db_app',
      schemaName: 'public',
      objectType: 'function',
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'fn_util_lookup_value_split_to_json',
      scriptType: 'sql',
      scriptOrder: '202',
      scriptPath:
        'db_app/public/util/functions/fn_util_lookup_value_split_to_json.sql',
    },
    {
      id: 203,
      databaseName: 'db_app',
      schemaName: 'public',
      objectType: 'function',
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'fn_util_lookup_value',
      scriptType: 'sql',
      scriptOrder: '203',
      scriptPath: 'db_app/public/util/functions/fn_util_lookup_value.sql',
    },
  ],
  rollbackScripts: [
    {
      id: 1,
      databaseName: 'db_app',
      schemaName: '*',
      objectType: 'rollback',
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: '01_rb_initial_setup_util_functions_and_plugins',
      scriptType: 'sql',
      scriptOrder: '0',
      scriptPath:
        'db_app/rollback-scripts/01_rb_initial_setup_util_functions_and_plugins.sql',
    },
  ],
};
