export const utilFunctionsAndPlugins = {
  runningScripts: [
    // TYPES
    {
      id: 100,
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'type_user_role_info',
      scriptType: 'running',
      scriptOrder: '100',
      scriptPath: 'db_app/public/util/type/type_user_role_info.sql',
    },

    // FUNCTIONS
    {
      id: 200,
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'util_fn_get_all_privileges',
      scriptType: 'running',
      scriptOrder: '200',
      scriptPath: 'db_app/public/util/function/util_fn_get_all_privileges.sql',
    },
    {
      id: 201,
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'util_fn_get_camel_case_split',
      scriptType: 'running',
      scriptOrder: '201',
      scriptPath: 'db_app/public/util/function/util_fn_get_camel_case_split.sql',
    },
    {
      id: 202,
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'util_fn_get_function_by_name',
      scriptType: 'running',
      scriptOrder: '202',
      scriptPath: 'db_app/public/util/function/util_fn_get_function_by_name.sql',
    },
    {
      id: 203,
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'util_fn_get_generate_random_string',
      scriptType: 'running',
      scriptOrder: '203',
      scriptPath: 'db_app/public/util/function/util_fn_get_generate_random_string.sql',
    },
    {
      id: 204,
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'util_fn_get_granted_privileges_by_user',
      scriptType: 'running',
      scriptOrder: '204',
      scriptPath: 'db_app/public/util/function/util_fn_get_granted_privileges_by_user.sql',
    },
    {
      id: 205,
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'util_fn_get_lookup_value_split_to_json',
      scriptType: 'running',
      scriptOrder: '205',
      scriptPath:
        'db_app/public/util/function/util_fn_get_lookup_value_split_to_json.sql',
    },
    {
      id: 206,
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'util_fn_get_lookup_value',
      scriptType: 'running',
      scriptOrder: '206',
      scriptPath: 'db_app/public/util/function/util_fn_get_lookup_value.sql',
    },
    {
      id: 207,
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'util_fn_get_procedure_by_name',
      scriptType: 'running',
      scriptOrder: '207',
      scriptPath: 'db_app/public/util/function/util_fn_get_procedure_by_name.sql',
    },
    {
      id: 208,
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'util_fn_get_schema_by_name',
      scriptType: 'running',
      scriptOrder: '208',
      scriptPath: 'db_app/public/util/function/util_fn_get_schema_by_name.sql',
    },
    {
      id: 209,
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'util_fn_get_table_by_name',
      scriptType: 'running',
      scriptOrder: '209',
      scriptPath: 'db_app/public/util/function/util_fn_get_table_by_name.sql',
    },
    {
      id: 210,
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'util_fn_get_trigger_by_name',
      scriptType: 'running',
      scriptOrder: '210',
      scriptPath: 'db_app/public/util/function/util_fn_get_trigger_by_name.sql',
    },
    {
      id: 211,
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: 'util_fn_get_user_role_info',
      scriptType: 'running',
      scriptOrder: '211',
      scriptPath: 'db_app/public/util/function/util_fn_get_user_role_info.sql',
    },
  ],
  rollbackScripts: [
    {
      id: 1,
      category: 'Initial Setup',
      migration: 'Util Functions And Plugins',
      scriptName: '01_rb_util_functions_and_plugins',
      scriptType: 'rollback',
      scriptOrder: '0',
      scriptPath:
        'db_app/rollback-scripts/initial_setup/01_rb_util_functions_and_plugins.sql',
    },
  ],
};
