export const migrationTablesAndFunctions = {
  runningScripts: [
    // TABLES
    {
      id: 1,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_category',
      scriptType: 'running',
      scriptOrder: '1',
      scriptPath: 'db_app/public/sys/table/migration_category.sql',
    },
    {
      id: 2,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration',
      scriptType: 'running',
      scriptOrder: '2',
      scriptPath: 'db_app/public/sys/table/migration.sql',
    },
    {
      id: 3,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_rollback',
      scriptType: 'running',
      scriptOrder: '3',
      scriptPath: 'db_app/public/sys/table/migration_rollback.sql',
    },
    {
      id: 4,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_script',
      scriptType: 'running',
      scriptOrder: '4',
      scriptPath: 'db_app/public/sys/table/migration_script.sql',
    },
    {
      id: 5,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_dependency',
      scriptType: 'running',
      scriptOrder: '5',
      scriptPath: 'db_app/public/sys/table/migration_dependency.sql',
    },
    {
      id: 6,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_tag',
      scriptType: 'running',
      scriptOrder: '6',
      scriptPath: 'db_app/public/sys/table/migration_tag.sql',
    },
    {
      id: 7,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_metadata',
      scriptType: 'running',
      scriptOrder: '7',
      scriptPath: 'db_app/public/sys/table/migration_metadata.sql',
    },
    // FUNCTIONS
    {
      id: 100,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_fn_get_all_migrations',
      scriptType: 'running',
      scriptOrder: '100',
      scriptPath: 'db_app/public/sys/function/migration_fn_get_all_migrations.sql',
    },
    {
      id: 101,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_fn_get_migration_by_id',
      scriptType: 'running',
      scriptOrder: '101',
      scriptPath:
        'db_app/public/sys/function/migration_fn_get_migration_by_id.sql',
    },
    {
      id: 102,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_fn_get_migration_rollback_id',
      scriptType: 'running',
      scriptOrder: '102',
      scriptPath: 'db_app/public/sys/function/migration_fn_get_migration_rollback_id.sql',
    },
    {
      id: 103,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_fn_get_migrations_by_category',
      scriptType: 'running',
      scriptOrder: '103',
      scriptPath: 'db_app/public/sys/function/migration_fn_get_migrations_by_category.sql',
    },
    {
      id: 104,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_fn_get_next_migration',
      scriptType: 'running',
      scriptOrder: '104',
      scriptPath: 'db_app/public/sys/function/migration_fn_get_next_migration.sql',
    },
    {
      id: 105,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_fn_get_previous_migration',
      scriptType: 'running',
      scriptOrder: '105',
      scriptPath:
        'db_app/public/sys/function/migration_fn_get_previous_migration.sql',
    },
    {
      id: 106,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_fn_get_scripts_for_migration',
      scriptType: 'running',
      scriptOrder: '106',
      scriptPath:
        'db_app/public/sys/function/migration_fn_get_scripts_for_migration.sql',
    },
    {
      id: 107,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_fn_get_rollbacks_for_migration',
      scriptType: 'running',
      scriptOrder: '107',
      scriptPath:
        'db_app/public/sys/function/migration_fn_get_rollbacks_for_migration.sql',
    },
    // PROCEDURES
    {
      id: 200,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_pr_get_all_migrations',
      scriptType: 'running',
      scriptOrder: '200',
      scriptPath:
        'db_app/public/sys/procedure/migration_pr_get_all_migrations.sql',
    },
    {
      id: 201,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_pr_get_rollbacks_for_migration',
      scriptType: 'running',
      scriptOrder: '201',
      scriptPath: 'db_app/public/sys/procedure/migration_pr_get_rollbacks_for_migration.sql',
    },
    {
      id: 202,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_pr_get_scripts_for_migration',
      scriptType: 'running',
      scriptOrder: '202',
      scriptPath:
        'db_app/public/sys/procedure/migration_pr_get_scripts_for_migration.sql',
    },
    {
      id: 203,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_pr_update_migration_completed',
      scriptType: 'running',
      scriptOrder: '203',
      scriptPath:
        'db_app/public/sys/procedure/migration_pr_update_migration_completed.sql',
    },
    {
      id: 204,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: 'migration_pr_update_migration_status',
      scriptType: 'running',
      scriptOrder: '204',
      scriptPath:
        'db_app/public/sys/procedure/migration_pr_update_migration_status.sql',
    },
  ],
  rollbackScripts: [
    {
      id: 1,
      category: 'Initial Setup',
      migration: 'Migration Tables And Functions',
      scriptName: '03_rb_initial_setup_migration_tables_and_funtions',
      scriptType: 'rollback',
      scriptOrder: '0',
      scriptPath:
        'db_app/rollback-scripts/03_rb_initial_setup_migration_tables_and_functions.sql',
    },
  ],
};
