@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@baseurl = http://{{host}}/api

### login
POST {{baseurl}}/auth/login
Content-Type: {{contentType}}

{
  "username": "gdo",
  "password": "123456"
}

### get user
GET {{baseurl}}/auth/login

### logout
GET {{baseurl}}/auth/logout


