export * from './auth/auth.route';
export * from './checkin/checkin.route';
export * from './clockin/clockin.route';
export * from './home/home.route';
export * from './config/config.route';
export * from './setup/setup.route';
export * from './account/account.route';
export * from './calendar/calendar.route';
export * from './admin/admin.route';
