export const initialSetup = [
  {
    migrationScripts: [
      // FUNCTIONS
      {
        id: 100,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'function',
        name: 'fn_drop_functions',
        scriptType: 'sql',
        scriptOrder: '100',
        scriptPath: 'scripts/public/function/_fn_drop_functions.sql',
      },
      {
        id: 101,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'function',
        name: 'fn_drop_procedures',
        scriptType: 'sql',
        scriptOrder: '101',
        scriptPath: 'scripts/public/function/_fn_drop_procedures.sql',
      },
      {
        id: 101,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'function',
        name: 'fn_drop_tables',
        scriptType: 'sql',
        scriptOrder: '102',
        scriptPath: 'scripts/public/function/_fn_drop_tables.sql',
      },
    ],
    rollbackScripts: [
      {
        id: 1,
        database: 'db_checkin',
        schema: '*',
        objectType: 'rollback',
        name: '00000_rb_initial_setup_funtions',
        scriptType: 'sql',
        scriptOrder: '0',
        scriptPath: 'rollbacks/00000_rb_initial_setup_functions.sql',
      },
    ],
  },
  {
    migrationScripts: [
      // TABLES
      {
        id: 1,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'table',
        name: 'config',
        scriptType: 'sql',
        scriptOrder: '0',
        scriptPath: 'scripts/main_sys/table/config.sql',
      },
      // FUNCTIONS
      {
        id: 100,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'function',
        name: 'fn_get_config_by_key',
        scriptType: 'sql',
        scriptOrder: '200',
        scriptPath: 'scripts/main_sys/function/fn_get_config_by_key.sql',
      },
      {
        id: 101,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'function',
        name: 'fn_is_config_key_boolean',
        scriptType: 'sql',
        scriptOrder: '101',
        scriptPath: 'scripts/main_sys/function/fn_is_config_key_boolean.sql',
      },
    ],
    rollbackScripts: [
      {
        id: 1,
        database: 'db_checkin',
        schema: '*',
        objectType: 'rollback',
        name: '00000_rb_initial_setup_configs',
        scriptType: 'sql',
        scriptOrder: '0',
        scriptPath: 'rollbacks/00000_rb_initial_setup_configs.sql',
      },
    ],
  },
  {
    migrationScripts: [
      // TABLES
      {
        id: 1,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'table',
        name: 'migration_category',
        scriptType: 'sql',
        scriptOrder: '0',
        scriptPath: 'scripts/main_sys/table/migration_category.sql',
      },
      {
        id: 2,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'table',
        name: 'migration',
        scriptType: 'sql',
        scriptOrder: '1',
        scriptPath: 'scripts/main_sys/table/migration.sql',
      },
      {
        id: 3,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'table',
        name: 'migration_rollback',
        scriptType: 'sql',
        scriptOrder: '2',
        scriptPath: 'scripts/main_sys/table/migration_rollback.sql',
      },
      {
        id: 4,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'table',
        name: 'migration_script',
        scriptType: 'sql',
        scriptOrder: '3',
        scriptPath: 'scripts/main_sys/table/migration_script.sql',
      },
      {
        id: 5,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'table',
        name: 'migration_dependency',
        scriptType: 'sql',
        scriptOrder: '4',
        scriptPath: 'scripts/main_sys/table/migration_dependency.sql',
      },
      {
        id: 6,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'table',
        name: 'migration_tag',
        scriptType: 'sql',
        scriptOrder: '5',
        scriptPath: 'scripts/main_sys/table/migration_tag.sql',
      },
      {
        id: 7,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'table',
        name: 'migration_metadata',
        scriptType: 'sql',
        scriptOrder: '6',
        scriptPath: 'scripts/main_sys/table/migration_metadata.sql',
      },
      // FUNCTIONS
      {
        id: 100,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'function',
        name: 'fn_get_migration_all',
        scriptType: 'sql',
        scriptOrder: '100',
        scriptPath: 'scripts/main_sys/function/fn_get_migration_all.sql',
      },
      {
        id: 101,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'function',
        name: 'fn_get_migration_by_category',
        scriptType: 'sql',
        scriptOrder: '101',
        scriptPath:
          'scripts/main_sys/function/fn_get_migration_by_category.sql',
      },
      {
        id: 102,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'function',
        name: 'fn_get_migration_by_id',
        scriptType: 'sql',
        scriptOrder: '102',
        scriptPath: 'scripts/main_sys/function/fn_get_migration_by_id.sql',
      },
      {
        id: 103,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'function',
        name: 'fn_get_migration_next',
        scriptType: 'sql',
        scriptOrder: '103',
        scriptPath: 'scripts/main_sys/function/fn_get_migration_next.sql',
      },
      {
        id: 104,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'function',
        name: 'fn_get_migration_previous',
        scriptType: 'sql',
        scriptOrder: '104',
        scriptPath: 'scripts/main_sys/function/fn_get_migration_previous.sql',
      },
      {
        id: 105,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'function',
        name: 'fn_get_migration_rollbacks_next',
        scriptType: 'sql',
        scriptOrder: '104',
        scriptPath:
          'scripts/main_sys/function/fn_get_migration_rollbacks_next.sql',
      },
      {
        id: 106,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'function',
        name: 'fn_get_migration_scripts_next',
        scriptType: 'sql',
        scriptOrder: '104',
        scriptPath:
          'scripts/main_sys/function/fn_get_migration_scripts_next.sql',
      },
      // PROCEDURES
      {
        id: 200,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'procedure',
        name: 'pr_migration_get_scripts',
        scriptType: 'sql',
        scriptOrder: '200',
        scriptPath: 'scripts/main_sys/procedure/pr_migration_get_scripts.sql',
      },
      {
        id: 201,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'procedure',
        name: 'pr_migration_update_status',
        scriptType: 'sql',
        scriptOrder: '201',
        scriptPath: 'scripts/main_sys/procedure/pr_migration_update_status.sql',
      },
      {
        id: 202,
        database: 'db_checkin',
        schema: 'main_sys',
        objectType: 'procedure',
        name: 'pr_migration_update_complete',
        scriptType: 'sql',
        scriptOrder: '202',
        scriptPath:
          'scripts/main_sys/procedure/pr_migration_update_complete.sql',
      },
    ],
    rollbackScripts: [
      {
        id: 1,
        database: 'db_checkin',
        schema: '*',
        objectType: 'rollback',
        name: '00000_rb_initial_setup_migrations',
        scriptType: 'sql',
        scriptOrder: '0',
        scriptPath: 'rollbacks/00000_rb_initial_setup_migrations.sql',
      },
    ],
  },
];
