export const initialFunctions = {
  scripts: [
    // FUNCTIONS
    {
      id: 100,
      databaseName: 'db_app',
      schemaName: 'public',
      objectType: 'function',
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'fn_get_function_by_name',
      scriptType: 'sql',
      scriptOrder: '100',
      scriptPath: 'db_app/public/init/functions/fn_get_function_by_name.sql',
    },
    {
      id: 101,
      databaseName: 'db_app',
      schemaName: 'public',
      objectType: 'function',
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'fn_get_procedure_by_name',
      scriptType: 'sql',
      scriptOrder: '101',
      scriptPath: 'db_app/public/init/functions/fn_get_procedure_by_name.sql',
    },
    {
      id: 102,
      databaseName: 'db_app',
      schemaName: 'public',
      objectType: 'function',
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'fn_get_schema_by_name',
      scriptType: 'sql',
      scriptOrder: '102',
      scriptPath: 'db_app/public/init/functions/fn_get_schema_by_name.sql',
    },
    {
      id: 103,
      databaseName: 'db_app',
      schemaName: 'public',
      objectType: 'function',
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'fn_get_table_by_name',
      scriptType: 'sql',
      scriptOrder: '103',
      scriptPath: 'db_app/public/init/functions/fn_get_table_by_name.sql',
    },
    {
      id: 104,
      databaseName: 'db_app',
      schemaName: 'public',
      objectType: 'function',
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'fn_get_trigger_by_name',
      scriptType: 'sql',
      scriptOrder: '104',
      scriptPath: 'db_app/public/init/functions/fn_get_trigger_by_name.sql',
    },
    // PROCEDURE
    {
      id: 200,
      databaseName: 'db_app',
      schemaName: 'public',
      objectType: 'procedure',
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'pr_drop_schemas',
      scriptType: 'sql',
      scriptOrder: '200',
      scriptPath: 'db_app/public/init/procedures/pr_drop_schemas.sql',
    },
    {
      id: 201,
      databaseName: 'db_app',
      schemaName: 'public',
      objectType: 'procedure',
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'pr_drop_functions',
      scriptType: 'sql',
      scriptOrder: '201',
      scriptPath: 'db_app/public/init/procedures/pr_drop_functions.sql',
    },
    {
      id: 202,
      databaseName: 'db_app',
      schemaName: 'public',
      objectType: 'procedure',
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'pr_drop_procedures',
      scriptType: 'sql',
      scriptOrder: '202',
      scriptPath: 'db_app/public/init/procedures/pr_drop_procedures.sql',
    },
    {
      id: 203,
      databaseName: 'db_app',
      schemaName: 'public',
      objectType: 'procedure',
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'pr_drop_tables',
      scriptType: 'sql',
      scriptOrder: '203',
      scriptPath: 'db_app/public/init/procedures/pr_drop_tables.sql',
    },
    {
      id: 204,
      databaseName: 'db_app',
      schemaName: 'public',
      objectType: 'procedure',
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'pr_create_schema',
      scriptType: 'sql',
      scriptOrder: '204',
      scriptPath: 'db_app/public/init/procedures/pr_create_schemas.sql',
    },
  ],
  rollbackScripts: [
    {
      id: 1,
      databaseName: 'db_app',
      schemaName: 'public',
      objectType: 'rollback',
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: '00_rb_initial_functions.sql',
      scriptType: 'sql',
      scriptOrder: '0',
      scriptPath: 'db_app/rollback-scripts/00_rb_initial_functions.sql',
    },
  ],
};
