import { Controller, Get, Param } from '@nestjs/common';

@Controller()
export class FormController {
  @Get()
  async getAllForms() {
    return [
      {
        id: 1,
        name: 'signup',
        title: 'Signup Form',
        description: 'Sample Form',
        data: [],
        version: 1,
      },
      {
        id: 2,
        name: 'login',
        title: 'Login Form',
        description: 'Sample Form',
        data: [],
        version: 1,
      },
    ];
  }

  @Get(':id')
  async getFormById(@Param('id') id: number) {
    if (id == 1) {
      return {
        id: 1,
        name: 'signup',
        title: 'Signup Form',
        description: 'Sample Form',
        data: [
          {
            id: 'k-9c37c',
            name: 'block',
            type: 'div',
            dataType: 'block',
            data: [],
            parentId: null,
            position: 0,
          },
          {
            id: 3,
            name: 'username',
            title: 'Username',
            type: 'text',
            dataType: 'field',
            data: null,
            parentId: 'k-9c37c',
            position: 1,
          },
          {
            id: 4,
            name: 'password',
            title: 'Password',
            type: 'text',
            dataType: 'field',
            data: null,
            parentId: null,
            position: 2,
          },
          {
            id: 'y-b5e58',
            name: 'block',
            type: 'div',
            dataType: 'block',
            data: [],
            parentId: null,
            position: 3,
          },
          {
            id: 5,
            name: 'email',
            title: 'Email',
            type: 'text',
            dataType: 'field',
            data: null,
            parentId: 'y-b5e58',
            position: 4,
          },
        ],
        fields: [
          {
            id: 1,
            name: 'first_name',
            title: 'First Name',
            type: 'text',
            dataType: 'field',
            data: null,
            parentId: 'k-9c37c',
            position: 1,
          },
          {
            id: 2,
            name: 'last_name',
            title: 'Last Name',
            type: 'text',
            dataType: 'field',
            data: null,
            parentId: 'k-9c37c',
            position: 2,
          },
          {
            id: 3,
            name: 'username',
            title: 'Username',
            type: 'text',
            dataType: 'field',
            data: null,
            parentId: 'k-9c37c',
            position: 3,
          },
          {
            id: 4,
            name: 'password',
            title: 'Password',
            type: 'text',
            dataType: 'field',
            data: null,
            parentId: null,
            position: 4,
          },
          {
            id: 5,
            name: 'email',
            title: 'Email',
            type: 'text',
            dataType: 'field',
            data: null,
            parentId: 'y-b5e58',
            position: 5,
          },
        ],
        version: 1,
      };
    } else if (id == 2) {
      return {
        id: 2,
        name: 'login',
        title: 'Login Form',
        description: 'Sample Form',
        data: [
          {
            id: 'x-69feb',
            name: 'block',
            type: 'div',
            dataType: 'block',
            data: [],
            parentId: null,
            position: 0,
          },
          {
            id: 3,
            name: 'username',
            title: 'Username',
            type: 'text',
            dataType: 'field',
            data: null,
            parentId: 'x-69feb',
            position: 1,
          },
          {
            id: 'b-9d4aa',
            name: 'block',
            type: 'div',
            dataType: 'block',
            data: [],
            parentId: null,
            position: 2,
          },
          {
            id: 4,
            name: 'password',
            title: 'Password',
            type: 'text',
            dataType: 'field',
            data: null,
            parentId: 'b-9d4aa',
            position: 3,
          },
        ],
        fields: [
          {
            id: 1,
            name: 'first_name',
            title: 'First Name',
            type: 'text',
            dataType: 'field',
            data: null,
            parentId: 'k-9c37c',
            position: 1,
          },
          {
            id: 2,
            name: 'last_name',
            title: 'Last Name',
            type: 'text',
            dataType: 'field',
            data: null,
            parentId: 'k-9c37c',
            position: 2,
          },
          {
            id: 3,
            name: 'username',
            title: 'Username',
            type: 'text',
            dataType: 'field',
            data: null,
            parentId: 'k-9c37c',
            position: 3,
          },
          {
            id: 4,
            name: 'password',
            title: 'Password',
            type: 'text',
            dataType: 'field',
            data: null,
            parentId: null,
            position: 4,
          },
          {
            id: 5,
            name: 'email',
            title: 'Email',
            type: 'text',
            dataType: 'field',
            data: null,
            parentId: 'y-b5e58',
            position: 5,
          },
        ],
        version: 1,
      };
    }
    return {};
  }
}
