export const initialFunctions = {
  runningScripts: [
    // FUNCTIONS
    {
      id: 105,
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'system_fn_create_schemas',
      scriptType: 'running',
      scriptOrder: '105',
      scriptPath: 'db_app/public/init/function/system_fn_create_schemas.sql',
    },
    {
      id: 106,
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'system_fn_drop_functions',
      scriptType: 'running',
      scriptOrder: '106',
      scriptPath: 'db_app/public/init/function/system_fn_drop_functions.sql',
    },
    {
      id: 107,
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'system_fn_drop_procedures',
      scriptType: 'running',
      scriptOrder: '107',
      scriptPath: 'db_app/public/init/function/system_fn_drop_procedures.sql',
    },
    {
      id: 108,
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'system_fn_drop_schemas',
      scriptType: 'running',
      scriptOrder: '108',
      scriptPath: 'db_app/public/init/function/system_fn_drop_schemas.sql',
    },
    {
      id: 109,
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'system_fn_drop_tables',
      scriptType: 'running',
      scriptOrder: '109',
      scriptPath: 'db_app/public/init/function/system_fn_drop_tables.sql',
    },
    {
      id: 110,
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'system_fn_drop_types',
      scriptType: 'running',
      scriptOrder: '110',
      scriptPath: 'db_app/public/init/function/system_fn_drop_types.sql',
    },
    {
      id: 111,
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'system_fn_drop_views',
      scriptType: 'running',
      scriptOrder: '111',
      scriptPath: 'db_app/public/init/function/system_fn_drop_views.sql',
    },
    {
      id: 112,
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'system_fn_execute_script',
      scriptType: 'running',
      scriptOrder: '112',
      scriptPath: 'db_app/public/init/function/system_fn_execute_script.sql',
    },
    // PROCEDURE
    {
      id: 200,
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'system_pr_drop_schemas',
      scriptType: 'running',
      scriptOrder: '200',
      scriptPath: 'db_app/public/init/procedure/system_pr_drop_schemas.sql',
    },
    {
      id: 201,
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'system_pr_drop_functions',
      scriptType: 'running',
      scriptOrder: '201',
      scriptPath: 'db_app/public/init/procedure/system_pr_drop_functions.sql',
    },
    {
      id: 202,
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'system_pr_drop_procedures',
      scriptType: 'running',
      scriptOrder: '202',
      scriptPath: 'db_app/public/init/procedure/system_pr_drop_procedures.sql',
    },
    {
      id: 203,
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'system_pr_drop_tables',
      scriptType: 'running',
      scriptOrder: '203',
      scriptPath: 'db_app/public/init/procedure/system_pr_drop_tables.sql',
    },
    {
      id: 204,
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'system_pr_drop_types',
      scriptType: 'running',
      scriptOrder: '204',
      scriptPath: 'db_app/public/init/procedure/system_pr_drop_types.sql',
    },
    {
      id: 205,
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'system_pr_create_schema',
      scriptType: 'running',
      scriptOrder: '205',
      scriptPath: 'db_app/public/init/procedure/system_pr_create_schemas.sql',
    },
  ],
  rollbackScripts: [
    {
      id: 1,
      category: 'Initial Setup',
      migration: 'Initial Functions',
      scriptName: 'rb_initial_functions.sql',
      scriptType: 'rollback',
      scriptOrder: '0',
      scriptPath: 'db_app/rollback-scripts/initial_setup/rb_initial_functions.sql',
    },
  ],
};
