export enum ModalActionType {
  OPEN_MODAL = 'OPEN_MODAL',
  CLOSE_MODAL = 'CLOSE_MODAL',
  RESIZE_MODAL = 'RESIZE_MODAL',
  DRAG_MODAL = 'DRAG_MODAL',
  SUBMIT_MODAL = 'SUBMIT_MODAL',
  CANCEL_MODAL = 'CANCEL_MODAL',
  CONFIRM_MODAL = 'CONFIRM_MODAL',
  CUSTOM_ACTION = 'CUSTOM_ACTION',
}