export enum ActionClickType {
  MENU_EDIT = 'MENU_EDIT',
  MENU_CLONE = 'MENU_CLONE',
  MENU_REMOVE = 'MENU_REMOVE',

  EDITOR_CLOSE = 'EDITOR_CLOSE',
  EDITOR_SAVE = 'EDITOR_SAVE',
  EDITOR_RESET = 'EDITOR_RESET',
}