export enum UserStatus {
  NOT_FOUND = 'USER_NOT_FOUND',
  ACTIVE = 'USER_ACTIVE',
  INACTIVE = 'USER_INACTIVE',
  REQUIRE_SETUP_ACCOUNT = 'USER_REQUIRE_SETUP_ACCOUNT',
  REQUIRE_VERIFY = 'USER_REQUIRE_VERIFY',
}
