@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@baseurl = http://{{host}}/api

### create user
POST {{baseurl}}/admin/users
Content-Type: {{contentType}}

{
  "username": "gdo",
  "password": "123456",
  "emailAddress": "gdo@gmail.com"
}

### get users
GET {{baseurl}}/admin/users?offset=1

### get user
GET {{baseurl}}/admin/users/1
Authorization: 'hello'

