CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS log.error (
    id UUID DEFAULT uuid_generate_v4() NOT NULL,

    message CHARACTER VARYING(255),
    host CHARACTER VARYING(45),
    url CHARACTER VARYING(45),
    stack TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    --
    PRIMARY KEY(id)
);