export const migrationData = {
  migrationFiles: [
    {
      id: 1,
      database: 'db_checkin',
      schema: 'main_sys',
      objectType: 'table',
      name: 'migration',
      scriptType: 'sql',
      scriptOrder: '0',
      scriptPath: 'scripts/main_sys/table/migration.sql',
    },
    {
      id: 2,
      database: 'db_checkin',
      schema: 'main_sys',
      objectType: 'table',
      name: 'migration',
      scriptType: 'sql',
      scriptOrder: '1',
      scriptPath: 'scripts/main_sys/table/migration_rollback.sql',
    },
    {
      id: 3,
      database: 'db_checkin',
      schema: 'main_sys',
      objectType: 'table',
      name: 'migration',
      scriptType: 'sql',
      scriptOrder: '2',
      scriptPath: 'scripts/main_sys/table/migration_script.sql',
    },
    {
      id: 4,
      database: 'db_checkin',
      schema: 'main_sys',
      objectType: 'table',
      name: 'migration',
      scriptType: 'sql',
      scriptOrder: '3',
      scriptPath: 'scripts/main_sys/table/migration_dependency.sql',
    },
    {
      id: 5,
      database: 'db_checkin',
      schema: 'main_sys',
      objectType: 'table',
      name: 'migration',
      scriptType: 'sql',
      scriptOrder: '4',
      scriptPath: 'scripts/main_sys/table/migration_tag.sql',
    },
    {
      id: 6,
      database: 'db_checkin',
      schema: 'main_sys',
      objectType: 'table',
      name: 'migration',
      scriptType: 'sql',
      scriptOrder: '5',
      scriptPath: 'scripts/main_sys/table/migration_metadata.sql',
    },
  ],
  rollbackFiles: [
    {
      id: 1,
      database: 'db_checkin',
      schema: '*',
      objectType: 'rollback',
      name: 'migration',
      scriptType: 'sql',
      scriptOrder: '0',
      scriptPath: 'rollbacks/do_drop_migrations.sql',
    },
  ],
};
